#!/usr/bin/env python

import sys, re

def main():
	if len(sys.argv) != 2:
		print "Usage: %s ***.cpp" % sys.argv[0]
		return

	status = 0
	fp = open(sys.argv[1])
	ln = fp.readline()
	while ln!="":
		lns = ln.strip()
		if lns.startswith("static int tolua_set_") and lns.endswith("(lua_State* tolua_S)"):
			#print ln
			if status!=0:
				raise "wrong format"
			status = 1
		elif status==1 and lns=="#endif":
			status = 2
		elif status==2:
			status = 0
			m = re.match(r"^self->([a-zA-Z_][a-zA-Z0-9_]*) = .+", lns)
			if not m:
				raise "double post_tolua???"
			#print m.group(0)
			#print m.group(1)
			print "self->backup(\"%s\", g_transaction_id);" % m.group(1)
		print ln.rstrip()
		ln = fp.readline()


if __name__ == "__main__":
	main()

