#
# Makefile 
#

TOP_SRCDIR = ..

include ../mk/gcc.defs.mk

CFLAGS   =-pipe -ggdb -Wall -D_XOPEN_SOURCE=500
LDFLAGS  =

OBJS = thread.o conf.o timer.o itimer.o ../io/pollio.o

EXES = marshal thread ctrl interval

all : $(EXES)

marshal : $(OBJS) marshal.o
	$(LD) $(LDFLAGS) $^ -o marshal

thread : $(OBJS) main.o
	$(LD) $(LDFLAGS) $^ -o thread

ctrl : ctrl.o
	$(LD) $(LDFLAGS) $^ -o ctrl

interval : interval.o
	$(LD) $(LDFLAGS) $(OBJS) interval.o -o interval

include ../mk/gcc.rules.mk

